from pathlib import Path
from datetime import datetime
import os
import shutil

import pandas as pd


# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------

DRY_RUN = True

CODE_DIRECTORY = Path(__file__).resolve().parent
AUTOMATION_DIRECTORY = CODE_DIRECTORY.parent
DOCUMENTS_DIRECTORY = AUTOMATION_DIRECTORY.parent

# Top-level folder containing the PDFs.
TARGET_DIRECTORY = DOCUMENTS_DIRECTORY / "Target"

# Folders used for rejected and held documents.
REJECTED_DIRECTORY = TARGET_DIRECTORY / "Rejected"
HOLD_DIRECTORY = TARGET_DIRECTORY / "Hold"

# The report generated by Script.py for the current date.
RESULTS_WORKBOOK = (
    AUTOMATION_DIRECTORY
    / f"RenameResults_{datetime.now().strftime('%Y-%m-%d')}.xlsx"
)


# ------------------------------------------------------------
# Display configuration
# ------------------------------------------------------------

print("Approval locations:")
print(f"  Target directory:  {TARGET_DIRECTORY}")
print(f"  Rejected folder:   {REJECTED_DIRECTORY}")
print(f"  Hold folder:       {HOLD_DIRECTORY}")
print(f"  Results workbook:  {RESULTS_WORKBOOK}")
print(f"  Dry run:           {DRY_RUN}")
print()


# ------------------------------------------------------------
# Validate paths
# ------------------------------------------------------------

if not TARGET_DIRECTORY.exists():
    raise FileNotFoundError(
        "The target directory could not be found:\n"
        f"{TARGET_DIRECTORY}"
    )

if not TARGET_DIRECTORY.is_dir():
    raise NotADirectoryError(
        "The configured target path is not a directory:\n"
        f"{TARGET_DIRECTORY}"
    )

if not RESULTS_WORKBOOK.exists():
    raise FileNotFoundError(
        "The reviewed results workbook could not be found:\n"
        f"{RESULTS_WORKBOOK}"
    )


# ------------------------------------------------------------
# Load reviewed results
# ------------------------------------------------------------

results = pd.read_excel(
    RESULTS_WORKBOOK,
    sheet_name="All Results",
    engine="openpyxl"
)


required_columns = [
    "Original File",
    "Generated Filename",
    "Status",
    "Manual Decision",
    "Approved Filename"
]


missing_columns = [
    column
    for column in required_columns
    if column not in results.columns
]


if missing_columns:
    raise ValueError(
        "The workbook is missing required columns: "
        + ", ".join(missing_columns)
    )


# ------------------------------------------------------------
# Clean manual decisions
# ------------------------------------------------------------

results["Manual Decision"] = (
    results["Manual Decision"]
    .fillna("")
    .astype(str)
    .str.strip()
    .str.upper()
)


valid_decisions = {
    "",
    "APPROVE",
    "REJECT",
    "HOLD"
}


invalid_decision_rows = results[
    ~results["Manual Decision"].isin(valid_decisions)
]


if not invalid_decision_rows.empty:

    print(
        "WARNING: Some rows contain invalid manual decisions."
    )

    print(
        "Only APPROVE, REJECT, HOLD, or blank are supported."
    )

    for _, row in invalid_decision_rows.iterrows():
        print(
            f"  {row['Original File']}: "
            f"{row['Manual Decision']}"
        )

    print()


# ------------------------------------------------------------
# Decision summary
# ------------------------------------------------------------

decision_counts = (
    results["Manual Decision"]
    .replace("", "BLANK")
    .value_counts(dropna=False)
)


print("Manual decision summary:")

for decision, count in decision_counts.items():
    print(f"  {decision}: {count}")

print()


# ------------------------------------------------------------
# Helper functions
# ------------------------------------------------------------

def paths_are_equal(first_path, second_path):
    """
    Compare two paths in a Windows-safe, case-insensitive manner.
    """

    return (
        os.path.normcase(
            str(first_path.resolve())
        )
        ==
        os.path.normcase(
            str(second_path.resolve())
        )
    )


def source_is_inside_target(source_path):
    """
    Return True only when the source file is inside the configured
    Target directory.
    """

    try:
        source_path.resolve().relative_to(
            TARGET_DIRECTORY.resolve()
        )

        return True

    except ValueError:
        return False


def validate_source(source_path):
    """
    Check whether a source path is eligible for processing.

    Returns:
        tuple: (is_valid, message)
    """

    if not source_path.exists():
        return (
            False,
            "Source file does not exist"
        )

    if not source_path.is_file():
        return (
            False,
            "Source path is not a file"
        )

    if source_path.suffix.lower() != ".pdf":
        return (
            False,
            "Source is not a PDF"
        )

    if not source_is_inside_target(source_path):
        return (
            False,
            "Source file is outside the configured Target directory"
        )

    return (
        True,
        ""
    )


def move_review_file(
    source_path,
    destination_directory,
    decision_name
):
    """
    Move a rejected or held PDF into the corresponding top-level
    Target folder.

    The original filename is retained.
    """

    destination_path = (
        destination_directory
        / source_path.name
    )

    print()
    print(f"{decision_name} source: {source_path}")
    print(f"{decision_name} target: {destination_path}")

    is_valid, validation_message = validate_source(
        source_path
    )

    if not is_valid:
        print(f"SKIPPED: {validation_message}")
        return (
            False,
            validation_message
        )

    if paths_are_equal(
        source_path,
        destination_path
    ):
        message = (
            f"File is already in the {decision_name} folder"
        )

        print(f"SKIPPED: {message}")

        return (
            True,
            message
        )

    if destination_path.exists():
        message = (
            f"Destination already exists: {destination_path}"
        )

        print(f"SKIPPED: {message}")

        return (
            False,
            message
        )

    if DRY_RUN:
        message = (
            f"Dry run - would move file to "
            f"{decision_name} folder"
        )

        print(message)

        return (
            True,
            message
        )

    destination_directory.mkdir(
        parents=True,
        exist_ok=True
    )

    shutil.move(
        str(source_path),
        str(destination_path)
    )

    message = f"Moved to {decision_name} folder"

    print(message)

    return (
        True,
        message
    )


def rename_approved_file(
    source_path,
    generated_filename,
    approved_filename
):
    """
    Rename a manually approved PDF.

    Approved Filename takes priority over Generated Filename.
    """

    if (
        pd.notna(approved_filename)
        and str(approved_filename).strip()
    ):
        final_filename = str(
            approved_filename
        ).strip()

        filename_source = "Approved Filename"

    elif (
        pd.notna(generated_filename)
        and str(generated_filename).strip()
    ):
        final_filename = str(
            generated_filename
        ).strip()

        filename_source = "Generated Filename"

    else:
        message = "No filename supplied"

        print()
        print(f"Approved source: {source_path}")
        print(f"SKIPPED: {message}")

        return (
            False,
            message
        )

    # Remove the extension if the reviewer included it.
    if final_filename.lower().endswith(".pdf"):
        final_filename = final_filename[:-4]

    # Prevent an accidental path from being entered as the filename.
    final_filename = Path(
        final_filename
    ).name

    destination_path = (
        source_path.parent
        / f"{final_filename}.pdf"
    )

    print()
    print(f"Approved source: {source_path}")
    print(f"Approved target: {destination_path}")
    print(f"Filename source: {filename_source}")

    is_valid, validation_message = validate_source(
        source_path
    )

    if not is_valid:
        print(f"SKIPPED: {validation_message}")

        return (
            False,
            validation_message
        )

    if paths_are_equal(
        source_path,
        destination_path
    ):
        message = "File is already correctly named"

        print(f"SKIPPED: {message}")

        return (
            True,
            message
        )

    if destination_path.exists():
        message = (
            f"Destination already exists: {destination_path}"
        )

        print(f"SKIPPED: {message}")

        return (
            False,
            message
        )

    if DRY_RUN:
        message = "Dry run - would rename approved file"

        print(message)

        return (
            True,
            message
        )

    source_path.rename(
        destination_path
    )

    message = "Renamed approved file"

    print(message)

    return (
        True,
        message
    )


# ------------------------------------------------------------
# Process manual decisions
# ------------------------------------------------------------

approved_count = 0
rejected_count = 0
hold_count = 0
blank_count = 0
invalid_count = 0
successful_operations = 0
skipped_operations = 0


for _, row in results.iterrows():

    decision = row["Manual Decision"]

    source_path = Path(
        str(row["Original File"])
    )

    generated_filename = row.get(
        "Generated Filename"
    )

    approved_filename = row.get(
        "Approved Filename"
    )

    # --------------------------------------------------------
    # APPROVE
    # --------------------------------------------------------

    if decision == "APPROVE":

        approved_count += 1

        success, message = rename_approved_file(
            source_path=source_path,
            generated_filename=generated_filename,
            approved_filename=approved_filename
        )

        if success:
            successful_operations += 1
        else:
            skipped_operations += 1

    # --------------------------------------------------------
    # REJECT
    # --------------------------------------------------------

    elif decision == "REJECT":

        rejected_count += 1

        success, message = move_review_file(
            source_path=source_path,
            destination_directory=REJECTED_DIRECTORY,
            decision_name="Rejected"
        )

        if success:
            successful_operations += 1
        else:
            skipped_operations += 1

    # --------------------------------------------------------
    # HOLD
    # --------------------------------------------------------

    elif decision == "HOLD":

        hold_count += 1

        success, message = move_review_file(
            source_path=source_path,
            destination_directory=HOLD_DIRECTORY,
            decision_name="Hold"
        )

        if success:
            successful_operations += 1
        else:
            skipped_operations += 1

    # --------------------------------------------------------
    # Blank
    # --------------------------------------------------------

    elif decision == "":

        blank_count += 1

        # Blank records are intentionally left untouched.

    # --------------------------------------------------------
    # Invalid value
    # --------------------------------------------------------

    else:

        invalid_count += 1

        print()
        print(f"Invalid decision for: {source_path}")
        print(f"SKIPPED: {decision}")


# ------------------------------------------------------------
# Final summary
# ------------------------------------------------------------

print()
print("=" * 70)
print("Approval processing summary")
print("=" * 70)

print(f"Approved rows:       {approved_count}")
print(f"Rejected rows:       {rejected_count}")
print(f"Hold rows:           {hold_count}")
print(f"Blank decisions:     {blank_count}")
print(f"Invalid decisions:   {invalid_count}")
print(f"Successful actions:  {successful_operations}")
print(f"Skipped actions:     {skipped_operations}")
print(f"Dry run:             {DRY_RUN}")

if DRY_RUN:
    print()
    print(
        "No files were renamed or moved because DRY_RUN is enabled."
    )
else:
    print()
    print(
        "Approved files were renamed and rejected/held files "
        "were moved where possible."
    )